#logging:
#  pattern:
#    console: "%d-%msg%n"
#  file: D:\个人文件\桌面\info.log
#  level: debug
##  path:"D:\个人文件\桌面\log.txt"
##    %d日期    %msg信息   %n换行
#配置数据库
#spring:
#  datasource:
#      url: jdbc:mysql://127.0.0.1:3306/weixin?characterEncoding=utf-8&useSSL=false
#      username: root
#      password: Bjfcm1c
#      driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  redis:
#    host: 172.18.18.235
#    port: 6379

server:
  port: 8091

spring:
  datasource:
      url: jdbc:oracle:thin:@127.0.0.1:1521/ORCL
      username: BPM_PX
      password: 88960687
      driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /templates/
      suffix: .html

